server:
  port: 8082

spring:
  application:
    name: service-feign

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:8081/eureka
    register-with-eureka: true
    fetch-registry: true #是否可检索
  instance:
    instance-id: feiqn-8082 # 自定义服务实例Id
    prefer-ip-address: true #访问路径可以显示IP地址
    lease-renewal-interval-in-seconds: 30 # client发送心跳的频率